name: "Issue Autolink"
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.6.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
<<<<<<< HEAD
          branch-prefix: "i"
=======
          branch-prefix: "issue"
>>>>>>> 5cc6ff14360b4c787ecf5de7be8900a76bdd1d4a
          resolve: "true"
